[2023-10-22T17:34:15.017+0800] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trick2g_insert_logs_dag.insert_logs_task manual__2023-10-22T09:34:04.357959+00:00 [queued]>
[2023-10-22T17:34:15.024+0800] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trick2g_insert_logs_dag.insert_logs_task manual__2023-10-22T09:34:04.357959+00:00 [queued]>
[2023-10-22T17:34:15.024+0800] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-22T17:34:15.035+0800] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_logs_task> on 2023-10-22 09:34:04.357959+00:00
[2023-10-22T17:34:15.041+0800] {standard_task_runner.py:57} INFO - Started process 507 to run task
[2023-10-22T17:34:15.047+0800] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'trick2g_insert_logs_dag', 'insert_logs_task', 'manual__2023-10-22T09:34:04.357959+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/dags_generator.py', '--cfg-path', '/tmp/tmpm5jmv1y_']
[2023-10-22T17:34:15.049+0800] {standard_task_runner.py:85} INFO - Job 63: Subtask insert_logs_task
[2023-10-22T17:34:15.089+0800] {task_command.py:415} INFO - Running <TaskInstance: trick2g_insert_logs_dag.insert_logs_task manual__2023-10-22T09:34:04.357959+00:00 [running]> on host 7781ba1548ef
[2023-10-22T17:34:15.144+0800] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trick2g_insert_logs_dag' AIRFLOW_CTX_TASK_ID='insert_logs_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T09:34:04.357959+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T09:34:04.357959+00:00'
[2023-10-22T17:34:16.873+0800] {logging_mixin.py:151} INFO - logs to send :  {'logGroupName': '/apps/CloudWatchAgentLog/', 'logStreamName': '172.31.5.38_i-017e875e2d5439eeb', 'logEvents': [{'timestamp': 1697967256873, 'message': "completed 'insert_logs_records' tasks: ['2023-10-15T02:00:12+08:00', '2023-10-09T00:47:24+08:00', '2023-10-13T01:00:13+08:00', '2023-10-14T02:44:11+08:00', '2023-10-16T03:57:44+08:00', '2023-10-08T06:10:34+08:00']"}], 'sequenceToken': '49039859564692077826586366770605634769390853740238805394'}
[2023-10-22T17:34:18.029+0800] {logging_mixin.py:151} INFO - Response :  {'nextSequenceToken': '49645354585863294957877295334747915074397260739485106962', 'ResponseMetadata': {'RequestId': 'eb92dbb3-8c62-4b45-bec0-f4f211872c11', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'eb92dbb3-8c62-4b45-bec0-f4f211872c11', 'content-type': 'application/x-amz-json-1.1', 'content-length': '80', 'date': 'Sun, 22 Oct 2023 09:34:18 GMT'}, 'RetryAttempts': 0}}
[2023-10-22T17:34:18.030+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:34:18.030+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:34:18.030+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:34:18.030+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:34:18.031+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:34:18.031+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:34:18.031+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:34:18.031+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:34:18.032+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:34:18.032+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:34:18.032+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:18.032+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:18.032+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:34:18.032+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:34:18.032+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:34:18.033+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:34:18.033+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:34:18.033+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:34:18.033+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:34:18.033+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:34:18.033+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:34:18.033+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:34:18.033+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:34:18.033+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:34:18.034+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:34:18.034+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:34:18.034+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:34:18.034+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:34:18.034+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:34:18.034+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:34:18.034+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:34:18.035+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:34:18.035+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:34:18.035+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:34:18.035+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:34:18.035+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:34:18.035+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:34:18.035+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:34:18.035+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:34:18.036+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:34:18.036+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:34:18.036+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:34:18.036+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:34:18.036+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:34:18.036+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:34:18.036+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:18.036+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:18.036+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:34:18.037+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:34:18.037+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:34:18.037+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:34:18.037+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:34:18.037+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:34:18.037+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:34:18.037+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:34:18.038+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:34:18.038+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:18.038+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:18.038+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:34:18.038+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:34:18.038+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:34:18.038+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:34:18.039+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:34:18.039+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:34:18.039+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:34:18.039+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:34:18.039+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:34:18.039+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:34:18.039+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:34:18.040+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 146, in insert_chat_logs
    dev_logger.info("completed 'insert_logs_records' tasks: ", insert_logs_records)
[2023-10-22T17:34:18.040+0800] {logging_mixin.py:151} WARNING - Message: "completed 'insert_logs_records' tasks: "
Arguments: (['2023-10-15T02:00:12+08:00', '2023-10-09T00:47:24+08:00', '2023-10-13T01:00:13+08:00', '2023-10-14T02:44:11+08:00', '2023-10-16T03:57:44+08:00', '2023-10-08T06:10:34+08:00'],)
[2023-10-22T17:34:18.040+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:34:18.040+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:34:18.040+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:34:18.040+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:34:18.040+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:34:18.040+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:34:18.041+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:34:18.041+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:34:18.041+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:34:18.041+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:34:18.041+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:18.041+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:18.041+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:34:18.042+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:34:18.042+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:34:18.042+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:34:18.042+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:34:18.042+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:34:18.042+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:34:18.042+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:34:18.042+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:34:18.043+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:34:18.043+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:34:18.043+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:34:18.043+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:34:18.043+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:34:18.043+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:34:18.044+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:34:18.044+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:34:18.044+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:34:18.044+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:34:18.044+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:34:18.044+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:34:18.045+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:34:18.045+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:34:18.045+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:34:18.045+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:34:18.045+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:34:18.046+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:34:18.046+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:34:18.046+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:34:18.046+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:34:18.046+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:34:18.046+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:34:18.047+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:34:18.047+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:18.047+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:18.047+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:34:18.047+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:34:18.048+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:34:18.048+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:34:18.048+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:34:18.048+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:34:18.048+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:34:18.049+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:34:18.049+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:34:18.049+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:18.049+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:18.049+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:34:18.050+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:34:18.050+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:34:18.050+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:34:18.050+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:34:18.050+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:34:18.050+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:34:18.051+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:34:18.051+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:34:18.051+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:34:18.051+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:34:18.051+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 146, in insert_chat_logs
    dev_logger.info("completed 'insert_logs_records' tasks: ", insert_logs_records)
[2023-10-22T17:34:18.051+0800] {logging_mixin.py:151} WARNING - Message: "completed 'insert_logs_records' tasks: "
Arguments: (['2023-10-15T02:00:12+08:00', '2023-10-09T00:47:24+08:00', '2023-10-13T01:00:13+08:00', '2023-10-14T02:44:11+08:00', '2023-10-16T03:57:44+08:00', '2023-10-08T06:10:34+08:00'],)
[2023-10-22T17:34:18.052+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:34:18.052+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:34:18.052+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:34:18.052+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:34:18.052+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:34:18.052+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:34:18.053+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:34:18.053+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:34:18.053+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:34:18.053+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:34:18.053+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:18.054+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:18.054+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:34:18.054+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:34:18.054+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:34:18.054+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:34:18.055+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:34:18.055+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:34:18.055+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:34:18.055+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:34:18.055+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:34:18.055+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:34:18.056+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:34:18.056+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:34:18.056+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:34:18.056+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:34:18.056+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:34:18.056+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:34:18.057+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:34:18.057+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:34:18.057+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:34:18.057+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:34:18.057+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:34:18.057+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:34:18.058+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:34:18.058+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:34:18.058+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:34:18.058+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:34:18.058+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:34:18.058+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:34:18.059+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:34:18.059+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:34:18.059+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:34:18.059+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:34:18.059+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:34:18.059+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:18.060+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:18.060+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:34:18.060+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:34:18.060+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:34:18.060+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:34:18.060+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:34:18.061+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:34:18.061+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:34:18.061+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:34:18.061+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:34:18.061+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:18.061+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:18.062+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:34:18.062+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:34:18.062+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:34:18.062+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:34:18.062+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:34:18.062+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:34:18.063+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:34:18.063+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:34:18.063+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:34:18.063+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:34:18.063+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:34:18.063+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 146, in insert_chat_logs
    dev_logger.info("completed 'insert_logs_records' tasks: ", insert_logs_records)
[2023-10-22T17:34:18.064+0800] {logging_mixin.py:151} WARNING - Message: "completed 'insert_logs_records' tasks: "
Arguments: (['2023-10-15T02:00:12+08:00', '2023-10-09T00:47:24+08:00', '2023-10-13T01:00:13+08:00', '2023-10-14T02:44:11+08:00', '2023-10-16T03:57:44+08:00', '2023-10-08T06:10:34+08:00'],)
[2023-10-22T17:34:18.064+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:34:18.064+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:34:18.064+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:34:18.064+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:34:18.065+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:34:18.065+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:34:18.065+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:34:18.065+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:34:18.066+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:34:18.066+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:34:18.066+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:18.066+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:18.066+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:34:18.067+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:34:18.067+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:34:18.067+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:34:18.067+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:34:18.067+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:34:18.067+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:34:18.068+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:34:18.068+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:34:18.068+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:34:18.068+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:34:18.068+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:34:18.068+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:34:18.069+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:34:18.069+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:34:18.069+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:34:18.069+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:34:18.069+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:34:18.069+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:34:18.070+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:34:18.070+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:34:18.070+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:34:18.070+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:34:18.070+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:34:18.070+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:34:18.071+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:34:18.071+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:34:18.071+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:34:18.071+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:34:18.071+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:34:18.071+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:34:18.072+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:34:18.072+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:34:18.072+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:18.072+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:18.072+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:34:18.072+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:34:18.073+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:34:18.073+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:34:18.073+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:34:18.073+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:34:18.073+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:34:18.074+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:34:18.074+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:34:18.074+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:18.074+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:18.074+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:34:18.074+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:34:18.075+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:34:18.075+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:34:18.075+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:34:18.075+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:34:18.075+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:34:18.075+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:34:18.076+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:34:18.076+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:34:18.076+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:34:18.076+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 146, in insert_chat_logs
    dev_logger.info("completed 'insert_logs_records' tasks: ", insert_logs_records)
[2023-10-22T17:34:18.076+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2023-10-22T17:34:18.076+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2023-10-22T17:34:18.077+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2023-10-22T17:34:18.077+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2023-10-22T17:34:18.077+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2023-10-22T17:34:18.077+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/log/file_task_handler.py", line 211, in emit
    self.handler.emit(record)
[2023-10-22T17:34:18.077+0800] {logging_mixin.py:151} WARNING - Message: "completed 'insert_logs_records' tasks: "
Arguments: (['2023-10-15T02:00:12+08:00', '2023-10-09T00:47:24+08:00', '2023-10-13T01:00:13+08:00', '2023-10-14T02:44:11+08:00', '2023-10-16T03:57:44+08:00', '2023-10-08T06:10:34+08:00'],)
[2023-10-22T17:34:18.228+0800] {logging_mixin.py:151} INFO - logs to send :  {'logGroupName': '/apps/CloudWatchAgentLog/', 'logStreamName': '172.31.5.38_i-017e875e2d5439eeb', 'logEvents': [{'timestamp': 1697967258229, 'message': "uncompleted insert_logs tasks: ['2023-10-17T00:13:27+08:00', '2023-10-22T08:10:54+08:00']"}], 'sequenceToken': '49039859564692077826586366770703358989906485079178549755'}
[2023-10-22T17:34:19.383+0800] {logging_mixin.py:151} INFO - Response :  {'nextSequenceToken': '49645309829851034416012495586604853004174671741146105346', 'ResponseMetadata': {'RequestId': 'ca383b6b-db9f-4541-8fa3-ad07524b1edd', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'ca383b6b-db9f-4541-8fa3-ad07524b1edd', 'content-type': 'application/x-amz-json-1.1', 'content-length': '80', 'date': 'Sun, 22 Oct 2023 09:34:19 GMT'}, 'RetryAttempts': 0}}
[2023-10-22T17:34:19.384+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:34:19.384+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:34:19.384+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:34:19.384+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:34:19.385+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:34:19.385+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:34:19.385+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:34:19.385+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:34:19.386+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:34:19.386+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:34:19.386+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:19.387+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:19.387+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:34:19.387+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:34:19.387+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:34:19.388+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:34:19.388+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:34:19.388+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:34:19.389+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:34:19.389+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:34:19.389+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:34:19.389+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:34:19.392+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:34:19.393+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:34:19.394+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:34:19.395+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:34:19.395+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:34:19.396+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:34:19.396+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:34:19.397+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:34:19.397+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:34:19.397+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:34:19.397+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:34:19.397+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:34:19.398+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:34:19.398+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:34:19.398+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:34:19.399+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:34:19.399+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:34:19.400+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:34:19.400+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:34:19.400+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:34:19.401+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:34:19.402+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:34:19.402+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:34:19.403+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:19.403+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:19.403+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:34:19.404+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:34:19.404+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:34:19.404+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:34:19.404+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:34:19.405+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:34:19.405+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:34:19.405+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:34:19.406+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:34:19.406+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:19.406+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:19.407+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:34:19.407+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:34:19.407+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:34:19.409+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:34:19.411+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:34:19.412+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:34:19.414+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:34:19.415+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:34:19.416+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:34:19.418+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:34:19.418+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:34:19.419+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 154, in insert_chat_logs
    dev_logger.info("uncompleted insert_logs tasks: ", uncompleted_tasks)
[2023-10-22T17:34:19.420+0800] {logging_mixin.py:151} WARNING - Message: 'uncompleted insert_logs tasks: '
Arguments: (['2023-10-17T00:13:27+08:00', '2023-10-22T08:10:54+08:00'],)
[2023-10-22T17:34:19.420+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:34:19.421+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:34:19.421+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:34:19.421+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:34:19.422+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:34:19.422+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:34:19.423+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:34:19.423+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:34:19.424+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:34:19.425+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:34:19.425+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:19.426+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:19.427+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:34:19.428+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:34:19.428+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:34:19.429+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:34:19.429+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:34:19.430+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:34:19.430+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:34:19.430+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:34:19.431+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:34:19.431+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:34:19.431+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:34:19.431+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:34:19.432+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:34:19.432+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:34:19.433+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:34:19.433+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:34:19.433+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:34:19.433+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:34:19.434+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:34:19.434+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:34:19.434+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:34:19.434+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:34:19.435+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:34:19.435+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:34:19.435+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:34:19.435+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:34:19.436+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:34:19.436+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:34:19.436+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:34:19.437+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:34:19.437+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:34:19.437+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:34:19.438+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:34:19.438+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:19.438+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:19.439+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:34:19.439+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:34:19.439+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:34:19.440+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:34:19.440+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:34:19.440+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:34:19.440+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:34:19.440+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:34:19.440+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:34:19.441+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:19.441+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:19.441+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:34:19.441+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:34:19.441+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:34:19.441+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:34:19.441+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:34:19.442+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:34:19.442+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:34:19.442+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:34:19.442+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:34:19.442+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:34:19.442+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:34:19.442+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 154, in insert_chat_logs
    dev_logger.info("uncompleted insert_logs tasks: ", uncompleted_tasks)
[2023-10-22T17:34:19.442+0800] {logging_mixin.py:151} WARNING - Message: 'uncompleted insert_logs tasks: '
Arguments: (['2023-10-17T00:13:27+08:00', '2023-10-22T08:10:54+08:00'],)
[2023-10-22T17:34:19.443+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:34:19.443+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:34:19.443+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:34:19.443+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:34:19.443+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:34:19.443+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:34:19.443+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:34:19.443+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:34:19.444+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:34:19.444+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:34:19.444+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:19.445+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:19.445+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:34:19.445+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:34:19.445+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:34:19.445+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:34:19.445+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:34:19.445+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:34:19.446+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:34:19.446+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:34:19.446+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:34:19.446+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:34:19.446+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:34:19.446+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:34:19.447+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:34:19.447+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:34:19.447+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:34:19.447+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:34:19.447+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:34:19.448+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:34:19.448+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:34:19.448+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:34:19.448+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:34:19.448+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:34:19.448+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:34:19.449+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:34:19.449+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:34:19.449+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:34:19.449+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:34:19.449+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:34:19.449+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:34:19.450+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:34:19.450+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:34:19.450+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:34:19.450+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:34:19.451+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:19.451+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:19.451+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:34:19.452+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:34:19.452+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:34:19.452+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:34:19.452+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:34:19.453+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:34:19.454+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:34:19.454+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:34:19.455+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:34:19.455+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:19.455+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:19.455+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:34:19.455+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:34:19.456+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:34:19.456+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:34:19.456+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:34:19.456+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:34:19.456+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:34:19.457+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:34:19.457+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:34:19.457+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:34:19.457+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:34:19.457+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 154, in insert_chat_logs
    dev_logger.info("uncompleted insert_logs tasks: ", uncompleted_tasks)
[2023-10-22T17:34:19.458+0800] {logging_mixin.py:151} WARNING - Message: 'uncompleted insert_logs tasks: '
Arguments: (['2023-10-17T00:13:27+08:00', '2023-10-22T08:10:54+08:00'],)
[2023-10-22T17:34:19.458+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:34:19.458+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:34:19.458+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:34:19.458+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:34:19.459+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:34:19.459+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:34:19.459+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:34:19.459+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:34:19.460+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:34:19.460+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:34:19.460+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:19.460+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:19.460+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:34:19.461+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:34:19.461+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:34:19.461+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:34:19.461+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:34:19.461+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:34:19.462+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:34:19.462+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:34:19.462+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:34:19.462+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:34:19.462+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:34:19.462+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:34:19.463+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:34:19.463+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:34:19.463+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:34:19.463+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:34:19.463+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:34:19.463+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:34:19.464+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:34:19.464+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:34:19.464+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:34:19.464+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:34:19.464+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:34:19.465+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:34:19.465+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:34:19.465+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:34:19.465+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:34:19.465+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:34:19.465+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:34:19.466+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:34:19.466+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:34:19.466+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:34:19.466+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:34:19.466+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:19.467+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:19.467+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:34:19.467+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:34:19.467+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:34:19.467+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:34:19.467+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:34:19.468+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:34:19.468+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:34:19.468+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:34:19.468+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:34:19.468+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:34:19.469+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:34:19.469+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:34:19.469+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:34:19.469+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:34:19.469+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:34:19.470+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:34:19.470+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:34:19.470+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:34:19.470+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:34:19.470+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:34:19.470+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:34:19.471+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:34:19.471+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 154, in insert_chat_logs
    dev_logger.info("uncompleted insert_logs tasks: ", uncompleted_tasks)
[2023-10-22T17:34:19.471+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2023-10-22T17:34:19.471+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2023-10-22T17:34:19.471+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2023-10-22T17:34:19.471+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2023-10-22T17:34:19.472+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2023-10-22T17:34:19.472+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/log/file_task_handler.py", line 211, in emit
    self.handler.emit(record)
[2023-10-22T17:34:19.472+0800] {logging_mixin.py:151} WARNING - Message: 'uncompleted insert_logs tasks: '
Arguments: (['2023-10-17T00:13:27+08:00', '2023-10-22T08:10:54+08:00'],)
[2023-10-22T17:34:19.472+0800] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
  File "/opt/airflow/plugins/features/viewers_reaction.py", line 159, in insert_chat_logs
    with open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/chat_logs/2023-10-17T00:13:27+08:00_trick2g.log'
[2023-10-22T17:34:19.486+0800] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=trick2g_insert_logs_dag, task_id=insert_logs_task, execution_date=20231022T093404, start_date=20231022T093415, end_date=20231022T093419
[2023-10-22T17:34:19.494+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 63 for task insert_logs_task ([Errno 2] No such file or directory: '/opt/airflow/data/chat_logs/2023-10-17T00:13:27+08:00_trick2g.log'; 507)
[2023-10-22T17:34:19.541+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T17:34:19.556+0800] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
