[2023-10-22T18:00:46.121+0800] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trick2g_insert_stats_dag.insert_stats_task manual__2023-10-22T10:00:33.780654+00:00 [queued]>
[2023-10-22T18:00:46.130+0800] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trick2g_insert_stats_dag.insert_stats_task manual__2023-10-22T10:00:33.780654+00:00 [queued]>
[2023-10-22T18:00:46.131+0800] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-22T18:00:46.184+0800] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_stats_task> on 2023-10-22 10:00:33.780654+00:00
[2023-10-22T18:00:46.191+0800] {standard_task_runner.py:57} INFO - Started process 981 to run task
[2023-10-22T18:00:46.200+0800] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'trick2g_insert_stats_dag', 'insert_stats_task', 'manual__2023-10-22T10:00:33.780654+00:00', '--job-id', '75', '--raw', '--subdir', 'DAGS_FOLDER/dags_generator.py', '--cfg-path', '/tmp/tmp6oe5tnih']
[2023-10-22T18:00:46.202+0800] {standard_task_runner.py:85} INFO - Job 75: Subtask insert_stats_task
[2023-10-22T18:00:46.249+0800] {task_command.py:415} INFO - Running <TaskInstance: trick2g_insert_stats_dag.insert_stats_task manual__2023-10-22T10:00:33.780654+00:00 [running]> on host 7781ba1548ef
[2023-10-22T18:00:46.311+0800] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trick2g_insert_stats_dag' AIRFLOW_CTX_TASK_ID='insert_stats_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T10:00:33.780654+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T10:00:33.780654+00:00'
[2023-10-22T18:00:46.319+0800] {log.py:232} WARNING - dev-INFO [viewers_reaction.py at line 355: viewers_reaction-insert_historical_stats]: (2023-10-22 18:00:46,319) trying to check uncompleted tasks for trick2g...
[2023-10-22T18:00:46.319+0800] {log.py:232} WARNING - dev-INFO [viewers_reaction.py at line 355: viewers_reaction-insert_historical_stats]: (2023-10-22 18:00:46,319) trying to check uncompleted tasks for trick2g...
[2023-10-22T18:00:46.320+0800] {log.py:232} WARNING - dev-INFO [viewers_reaction.py at line 355: viewers_reaction-insert_historical_stats]: (2023-10-22 18:00:46,319) trying to check uncompleted tasks for trick2g...
[2023-10-22T18:00:46.319+0800] {viewers_reaction.py:355} INFO - trying to check uncompleted tasks for trick2g...
[2023-10-22T18:00:47.219+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T18:00:47.219+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T18:00:47.220+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T18:00:47.220+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T18:00:47.220+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T18:00:47.220+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T18:00:47.220+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T18:00:47.221+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T18:00:47.221+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T18:00:47.221+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T18:00:47.222+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.222+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.222+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T18:00:47.222+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T18:00:47.222+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T18:00:47.223+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T18:00:47.223+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T18:00:47.223+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T18:00:47.223+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T18:00:47.223+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T18:00:47.223+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T18:00:47.224+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T18:00:47.224+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T18:00:47.224+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T18:00:47.224+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T18:00:47.224+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T18:00:47.224+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T18:00:47.224+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T18:00:47.225+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T18:00:47.225+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T18:00:47.225+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T18:00:47.225+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T18:00:47.225+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T18:00:47.225+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T18:00:47.226+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T18:00:47.226+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T18:00:47.226+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T18:00:47.226+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T18:00:47.226+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T18:00:47.226+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T18:00:47.227+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T18:00:47.227+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T18:00:47.227+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T18:00:47.227+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T18:00:47.227+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T18:00:47.227+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.228+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.228+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T18:00:47.228+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T18:00:47.228+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T18:00:47.228+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T18:00:47.228+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T18:00:47.229+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T18:00:47.229+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T18:00:47.229+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T18:00:47.229+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T18:00:47.229+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.229+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.230+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T18:00:47.230+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T18:00:47.230+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T18:00:47.230+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T18:00:47.230+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T18:00:47.230+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T18:00:47.231+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T18:00:47.231+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T18:00:47.231+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T18:00:47.231+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T18:00:47.231+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 73, in insert_stats_task
    analyser.insert_historical_stats()
[2023-10-22T18:00:47.231+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 366, in insert_historical_stats
    dev_logger.info("completed insert_logs tasks: ", insert_logs_task_records)
[2023-10-22T18:00:47.232+0800] {logging_mixin.py:151} WARNING - Message: 'completed insert_logs tasks: '
Arguments: (['2023-10-15T02:00:12+08:00', '2023-10-22T08:10:54+08:00', '2023-10-09T00:47:24+08:00', '2023-10-13T01:00:13+08:00', '2023-10-14T02:44:11+08:00', '2023-10-16T03:57:44+08:00', '2023-10-08T06:10:34+08:00'],)
[2023-10-22T18:00:47.232+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T18:00:47.232+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T18:00:47.232+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T18:00:47.232+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T18:00:47.232+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T18:00:47.233+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T18:00:47.233+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T18:00:47.233+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T18:00:47.233+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T18:00:47.234+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T18:00:47.234+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.234+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.234+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T18:00:47.234+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T18:00:47.235+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T18:00:47.235+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T18:00:47.235+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T18:00:47.235+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T18:00:47.235+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T18:00:47.235+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T18:00:47.236+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T18:00:47.236+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T18:00:47.236+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T18:00:47.236+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T18:00:47.236+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T18:00:47.236+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T18:00:47.237+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T18:00:47.237+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T18:00:47.237+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T18:00:47.237+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T18:00:47.237+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T18:00:47.238+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T18:00:47.238+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T18:00:47.238+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T18:00:47.238+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T18:00:47.238+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T18:00:47.238+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T18:00:47.239+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T18:00:47.239+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T18:00:47.239+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T18:00:47.239+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T18:00:47.239+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T18:00:47.239+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T18:00:47.240+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T18:00:47.240+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T18:00:47.240+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.240+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.240+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T18:00:47.241+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T18:00:47.241+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T18:00:47.241+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T18:00:47.241+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T18:00:47.241+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T18:00:47.242+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T18:00:47.242+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T18:00:47.242+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T18:00:47.242+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.242+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.242+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T18:00:47.243+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T18:00:47.243+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T18:00:47.243+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T18:00:47.243+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T18:00:47.243+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T18:00:47.244+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T18:00:47.244+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T18:00:47.244+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T18:00:47.244+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T18:00:47.244+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 73, in insert_stats_task
    analyser.insert_historical_stats()
[2023-10-22T18:00:47.244+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 366, in insert_historical_stats
    dev_logger.info("completed insert_logs tasks: ", insert_logs_task_records)
[2023-10-22T18:00:47.245+0800] {logging_mixin.py:151} WARNING - Message: 'completed insert_logs tasks: '
Arguments: (['2023-10-15T02:00:12+08:00', '2023-10-22T08:10:54+08:00', '2023-10-09T00:47:24+08:00', '2023-10-13T01:00:13+08:00', '2023-10-14T02:44:11+08:00', '2023-10-16T03:57:44+08:00', '2023-10-08T06:10:34+08:00'],)
[2023-10-22T18:00:47.245+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T18:00:47.245+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T18:00:47.245+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T18:00:47.245+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T18:00:47.245+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T18:00:47.245+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T18:00:47.246+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T18:00:47.246+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T18:00:47.246+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T18:00:47.246+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T18:00:47.247+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.247+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.247+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T18:00:47.247+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T18:00:47.247+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T18:00:47.247+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T18:00:47.248+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T18:00:47.248+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T18:00:47.248+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T18:00:47.248+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T18:00:47.248+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T18:00:47.248+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T18:00:47.248+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T18:00:47.249+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T18:00:47.249+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T18:00:47.249+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T18:00:47.249+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T18:00:47.249+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T18:00:47.249+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T18:00:47.250+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T18:00:47.250+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T18:00:47.250+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T18:00:47.250+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T18:00:47.250+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T18:00:47.251+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T18:00:47.251+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T18:00:47.251+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T18:00:47.251+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T18:00:47.251+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T18:00:47.251+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T18:00:47.251+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T18:00:47.252+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T18:00:47.252+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T18:00:47.252+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T18:00:47.252+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T18:00:47.252+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.253+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.253+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T18:00:47.253+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T18:00:47.253+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T18:00:47.253+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T18:00:47.253+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T18:00:47.254+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T18:00:47.254+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T18:00:47.254+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T18:00:47.254+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T18:00:47.254+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.254+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.255+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T18:00:47.255+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T18:00:47.255+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T18:00:47.255+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T18:00:47.255+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T18:00:47.255+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T18:00:47.256+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T18:00:47.256+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T18:00:47.256+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T18:00:47.256+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T18:00:47.256+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 73, in insert_stats_task
    analyser.insert_historical_stats()
[2023-10-22T18:00:47.257+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 366, in insert_historical_stats
    dev_logger.info("completed insert_logs tasks: ", insert_logs_task_records)
[2023-10-22T18:00:47.257+0800] {logging_mixin.py:151} WARNING - Message: 'completed insert_logs tasks: '
Arguments: (['2023-10-15T02:00:12+08:00', '2023-10-22T08:10:54+08:00', '2023-10-09T00:47:24+08:00', '2023-10-13T01:00:13+08:00', '2023-10-14T02:44:11+08:00', '2023-10-16T03:57:44+08:00', '2023-10-08T06:10:34+08:00'],)
[2023-10-22T18:00:47.257+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T18:00:47.257+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T18:00:47.257+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T18:00:47.258+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T18:00:47.258+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T18:00:47.258+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T18:00:47.258+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T18:00:47.258+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T18:00:47.259+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T18:00:47.259+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T18:00:47.259+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.259+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.260+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T18:00:47.260+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T18:00:47.260+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T18:00:47.260+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T18:00:47.260+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T18:00:47.260+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T18:00:47.261+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T18:00:47.261+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T18:00:47.261+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T18:00:47.261+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T18:00:47.261+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T18:00:47.262+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T18:00:47.262+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T18:00:47.262+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T18:00:47.262+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T18:00:47.262+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T18:00:47.262+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T18:00:47.262+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T18:00:47.263+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T18:00:47.263+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T18:00:47.263+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T18:00:47.263+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T18:00:47.263+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T18:00:47.264+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T18:00:47.264+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T18:00:47.264+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T18:00:47.264+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T18:00:47.264+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T18:00:47.264+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T18:00:47.265+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T18:00:47.265+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T18:00:47.265+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T18:00:47.265+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T18:00:47.265+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.265+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.266+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T18:00:47.266+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T18:00:47.266+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T18:00:47.266+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T18:00:47.266+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T18:00:47.267+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T18:00:47.267+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T18:00:47.267+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T18:00:47.267+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T18:00:47.267+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.267+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.268+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T18:00:47.268+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T18:00:47.268+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T18:00:47.268+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T18:00:47.268+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T18:00:47.268+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T18:00:47.269+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T18:00:47.269+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T18:00:47.269+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T18:00:47.269+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T18:00:47.269+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 73, in insert_stats_task
    analyser.insert_historical_stats()
[2023-10-22T18:00:47.270+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 366, in insert_historical_stats
    dev_logger.info("completed insert_logs tasks: ", insert_logs_task_records)
[2023-10-22T18:00:47.270+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2023-10-22T18:00:47.270+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2023-10-22T18:00:47.270+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2023-10-22T18:00:47.270+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2023-10-22T18:00:47.270+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2023-10-22T18:00:47.270+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/log/file_task_handler.py", line 211, in emit
    self.handler.emit(record)
[2023-10-22T18:00:47.271+0800] {logging_mixin.py:151} WARNING - Message: 'completed insert_logs tasks: '
Arguments: (['2023-10-15T02:00:12+08:00', '2023-10-22T08:10:54+08:00', '2023-10-09T00:47:24+08:00', '2023-10-13T01:00:13+08:00', '2023-10-14T02:44:11+08:00', '2023-10-16T03:57:44+08:00', '2023-10-08T06:10:34+08:00'],)
[2023-10-22T18:00:47.415+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T18:00:47.416+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T18:00:47.416+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T18:00:47.416+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T18:00:47.417+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T18:00:47.417+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T18:00:47.417+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T18:00:47.417+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T18:00:47.419+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T18:00:47.419+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T18:00:47.419+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.420+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.420+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T18:00:47.420+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T18:00:47.420+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T18:00:47.421+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T18:00:47.421+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T18:00:47.421+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T18:00:47.422+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T18:00:47.422+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T18:00:47.422+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T18:00:47.422+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T18:00:47.423+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T18:00:47.423+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T18:00:47.423+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T18:00:47.423+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T18:00:47.424+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T18:00:47.424+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T18:00:47.424+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T18:00:47.424+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T18:00:47.425+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T18:00:47.425+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T18:00:47.425+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T18:00:47.425+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T18:00:47.426+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T18:00:47.426+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T18:00:47.426+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T18:00:47.427+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T18:00:47.427+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T18:00:47.427+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T18:00:47.427+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T18:00:47.428+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T18:00:47.428+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T18:00:47.428+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T18:00:47.428+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T18:00:47.429+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.429+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.429+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T18:00:47.429+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T18:00:47.430+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T18:00:47.430+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T18:00:47.430+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T18:00:47.431+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T18:00:47.431+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T18:00:47.431+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T18:00:47.431+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T18:00:47.431+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.432+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.432+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T18:00:47.432+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T18:00:47.433+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T18:00:47.433+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T18:00:47.433+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T18:00:47.433+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T18:00:47.434+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T18:00:47.434+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T18:00:47.434+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T18:00:47.434+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T18:00:47.435+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 73, in insert_stats_task
    analyser.insert_historical_stats()
[2023-10-22T18:00:47.435+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 399, in insert_historical_stats
    dev_logger.info("completed insert_stats tasks: ", insert_stats_task_records)
[2023-10-22T18:00:47.435+0800] {logging_mixin.py:151} WARNING - Message: 'completed insert_stats tasks: '
Arguments: (['2023-10-08T06:10:34+08:00', '2023-10-13T01:00:13+08:00', '2023-10-09T00:47:24+08:00', '2023-10-16T03:57:44+08:00', '2023-10-14T02:44:11+08:00', '2023-10-15T02:00:12+08:00'],)
[2023-10-22T18:00:47.436+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T18:00:47.436+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T18:00:47.436+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T18:00:47.436+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T18:00:47.437+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T18:00:47.437+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T18:00:47.437+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T18:00:47.437+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T18:00:47.438+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T18:00:47.439+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T18:00:47.439+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.439+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.439+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T18:00:47.440+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T18:00:47.444+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T18:00:47.445+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T18:00:47.445+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T18:00:47.447+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T18:00:47.447+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T18:00:47.447+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T18:00:47.448+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T18:00:47.448+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T18:00:47.448+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T18:00:47.449+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T18:00:47.449+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T18:00:47.449+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T18:00:47.449+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T18:00:47.450+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T18:00:47.450+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T18:00:47.450+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T18:00:47.450+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T18:00:47.451+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T18:00:47.451+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T18:00:47.451+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T18:00:47.451+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T18:00:47.452+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T18:00:47.452+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T18:00:47.452+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T18:00:47.453+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T18:00:47.453+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T18:00:47.453+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T18:00:47.453+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T18:00:47.454+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T18:00:47.454+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T18:00:47.466+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T18:00:47.468+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.471+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.471+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T18:00:47.473+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T18:00:47.474+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T18:00:47.476+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T18:00:47.478+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T18:00:47.480+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T18:00:47.481+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T18:00:47.481+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T18:00:47.482+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T18:00:47.483+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.485+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.487+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T18:00:47.489+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T18:00:47.490+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T18:00:47.490+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T18:00:47.491+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T18:00:47.491+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T18:00:47.491+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T18:00:47.491+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T18:00:47.492+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T18:00:47.492+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T18:00:47.492+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 73, in insert_stats_task
    analyser.insert_historical_stats()
[2023-10-22T18:00:47.492+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 399, in insert_historical_stats
    dev_logger.info("completed insert_stats tasks: ", insert_stats_task_records)
[2023-10-22T18:00:47.492+0800] {logging_mixin.py:151} WARNING - Message: 'completed insert_stats tasks: '
Arguments: (['2023-10-08T06:10:34+08:00', '2023-10-13T01:00:13+08:00', '2023-10-09T00:47:24+08:00', '2023-10-16T03:57:44+08:00', '2023-10-14T02:44:11+08:00', '2023-10-15T02:00:12+08:00'],)
[2023-10-22T18:00:47.493+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T18:00:47.493+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T18:00:47.493+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T18:00:47.494+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T18:00:47.494+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T18:00:47.494+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T18:00:47.494+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T18:00:47.494+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T18:00:47.495+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T18:00:47.495+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T18:00:47.496+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.496+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.496+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T18:00:47.496+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T18:00:47.496+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T18:00:47.497+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T18:00:47.497+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T18:00:47.497+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T18:00:47.497+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T18:00:47.498+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T18:00:47.498+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T18:00:47.498+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T18:00:47.498+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T18:00:47.498+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T18:00:47.499+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T18:00:47.499+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T18:00:47.500+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T18:00:47.500+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T18:00:47.501+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T18:00:47.501+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T18:00:47.502+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T18:00:47.502+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T18:00:47.502+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T18:00:47.503+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T18:00:47.503+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T18:00:47.504+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T18:00:47.504+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T18:00:47.504+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T18:00:47.504+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T18:00:47.505+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T18:00:47.505+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T18:00:47.505+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T18:00:47.505+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T18:00:47.506+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T18:00:47.506+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T18:00:47.506+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.506+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.507+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T18:00:47.507+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T18:00:47.507+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T18:00:47.507+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T18:00:47.508+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T18:00:47.508+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T18:00:47.508+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T18:00:47.508+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T18:00:47.509+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T18:00:47.509+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.509+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.509+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T18:00:47.509+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T18:00:47.510+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T18:00:47.510+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T18:00:47.510+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T18:00:47.511+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T18:00:47.511+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T18:00:47.511+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T18:00:47.511+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T18:00:47.511+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T18:00:47.512+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 73, in insert_stats_task
    analyser.insert_historical_stats()
[2023-10-22T18:00:47.512+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 399, in insert_historical_stats
    dev_logger.info("completed insert_stats tasks: ", insert_stats_task_records)
[2023-10-22T18:00:47.512+0800] {logging_mixin.py:151} WARNING - Message: 'completed insert_stats tasks: '
Arguments: (['2023-10-08T06:10:34+08:00', '2023-10-13T01:00:13+08:00', '2023-10-09T00:47:24+08:00', '2023-10-16T03:57:44+08:00', '2023-10-14T02:44:11+08:00', '2023-10-15T02:00:12+08:00'],)
[2023-10-22T18:00:47.512+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T18:00:47.513+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T18:00:47.513+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T18:00:47.513+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T18:00:47.513+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T18:00:47.514+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T18:00:47.514+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T18:00:47.514+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T18:00:47.515+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T18:00:47.515+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T18:00:47.516+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.516+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.516+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T18:00:47.516+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T18:00:47.517+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T18:00:47.517+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T18:00:47.517+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T18:00:47.517+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T18:00:47.518+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T18:00:47.518+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T18:00:47.518+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T18:00:47.518+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T18:00:47.519+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T18:00:47.519+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T18:00:47.519+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T18:00:47.519+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T18:00:47.520+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T18:00:47.520+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T18:00:47.520+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T18:00:47.520+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T18:00:47.521+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T18:00:47.521+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T18:00:47.521+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T18:00:47.521+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T18:00:47.522+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T18:00:47.522+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T18:00:47.523+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T18:00:47.524+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T18:00:47.524+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T18:00:47.526+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T18:00:47.526+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T18:00:47.526+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T18:00:47.527+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T18:00:47.527+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T18:00:47.528+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T18:00:47.528+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.528+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.528+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T18:00:47.528+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T18:00:47.529+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T18:00:47.529+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T18:00:47.529+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T18:00:47.529+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T18:00:47.529+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T18:00:47.530+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T18:00:47.530+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T18:00:47.530+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T18:00:47.530+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T18:00:47.530+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T18:00:47.531+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T18:00:47.531+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T18:00:47.531+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T18:00:47.532+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T18:00:47.532+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T18:00:47.533+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T18:00:47.533+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T18:00:47.534+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T18:00:47.534+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T18:00:47.535+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 73, in insert_stats_task
    analyser.insert_historical_stats()
[2023-10-22T18:00:47.535+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 399, in insert_historical_stats
    dev_logger.info("completed insert_stats tasks: ", insert_stats_task_records)
[2023-10-22T18:00:47.536+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2023-10-22T18:00:47.536+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2023-10-22T18:00:47.537+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2023-10-22T18:00:47.537+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2023-10-22T18:00:47.538+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2023-10-22T18:00:47.539+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/log/file_task_handler.py", line 211, in emit
    self.handler.emit(record)
[2023-10-22T18:00:47.539+0800] {logging_mixin.py:151} WARNING - Message: 'completed insert_stats tasks: '
Arguments: (['2023-10-08T06:10:34+08:00', '2023-10-13T01:00:13+08:00', '2023-10-09T00:47:24+08:00', '2023-10-16T03:57:44+08:00', '2023-10-14T02:44:11+08:00', '2023-10-15T02:00:12+08:00'],)
[2023-10-22T18:00:47.540+0800] {logging_mixin.py:151} INFO - uncompleted_tasks:  ['2023-10-22T08:10:54+08:00']
[2023-10-22T18:00:47.540+0800] {log.py:232} WARNING - dev-INFO [viewers_reaction.py at line 410: viewers_reaction-insert_historical_stats]: (2023-10-22 18:00:47,540) trick2g's live stream started at 2023-10-22T08:10:54+08:00 has not been calculated and inserted.
[2023-10-22T18:00:47.541+0800] {log.py:232} WARNING - dev-INFO [viewers_reaction.py at line 410: viewers_reaction-insert_historical_stats]: (2023-10-22 18:00:47,540) trick2g's live stream started at 2023-10-22T08:10:54+08:00 has not been calculated and inserted.
[2023-10-22T18:00:47.541+0800] {log.py:232} WARNING - dev-INFO [viewers_reaction.py at line 410: viewers_reaction-insert_historical_stats]: (2023-10-22 18:00:47,540) trick2g's live stream started at 2023-10-22T08:10:54+08:00 has not been calculated and inserted.
[2023-10-22T18:00:47.540+0800] {viewers_reaction.py:410} INFO - trick2g's live stream started at 2023-10-22T08:10:54+08:00 has not been calculated and inserted.
[2023-10-22T18:00:47.542+0800] {logging_mixin.py:151} INFO - viewers_reaction: querying historical_stats...
[2023-10-22T18:00:47.839+0800] {logging_mixin.py:151} INFO - (skipped) viewers_reaction: calculating sentiment_score...
[2023-10-22T18:00:47.839+0800] {log.py:232} WARNING - dev-INFO [viewers_reaction.py at line 424: viewers_reaction-insert_historical_stats]: (2023-10-22 18:00:47,839) viewers_reaction: trying to insertmany into chatStats...
[2023-10-22T18:00:47.839+0800] {log.py:232} WARNING - dev-INFO [viewers_reaction.py at line 424: viewers_reaction-insert_historical_stats]: (2023-10-22 18:00:47,839) viewers_reaction: trying to insertmany into chatStats...
[2023-10-22T18:00:47.840+0800] {log.py:232} WARNING - dev-INFO [viewers_reaction.py at line 424: viewers_reaction-insert_historical_stats]: (2023-10-22 18:00:47,839) viewers_reaction: trying to insertmany into chatStats...
[2023-10-22T18:00:47.839+0800] {viewers_reaction.py:424} INFO - viewers_reaction: trying to insertmany into chatStats...
[2023-10-22T18:00:47.997+0800] {log.py:232} WARNING - dev-INFO [viewers_reaction.py at line 428: viewers_reaction-insert_historical_stats]: (2023-10-22 18:00:47,997) successfully insert historical stats.
[2023-10-22T18:00:47.998+0800] {log.py:232} WARNING - dev-INFO [viewers_reaction.py at line 428: viewers_reaction-insert_historical_stats]: (2023-10-22 18:00:47,997) successfully insert historical stats.
[2023-10-22T18:00:47.998+0800] {log.py:232} WARNING - dev-INFO [viewers_reaction.py at line 428: viewers_reaction-insert_historical_stats]: (2023-10-22 18:00:47,997) successfully insert historical stats.
[2023-10-22T18:00:47.997+0800] {viewers_reaction.py:428} INFO - successfully insert historical stats.
[2023-10-22T18:00:47.998+0800] {logging_mixin.py:151} INFO - successfully insert historical stats.
[2023-10-22T18:00:47.998+0800] {logging_mixin.py:151} INFO - viewers_reaction: trying to insert 'insert_stats' task record into taskRecords...
[2023-10-22T18:00:48.143+0800] {log.py:232} WARNING - dev-INFO [viewers_reaction.py at line 451: viewers_reaction-insert_historical_stats]: (2023-10-22 18:00:48,143) successfully insert task records.
[2023-10-22T18:00:48.143+0800] {log.py:232} WARNING - dev-INFO [viewers_reaction.py at line 451: viewers_reaction-insert_historical_stats]: (2023-10-22 18:00:48,143) successfully insert task records.
[2023-10-22T18:00:48.144+0800] {log.py:232} WARNING - dev-INFO [viewers_reaction.py at line 451: viewers_reaction-insert_historical_stats]: (2023-10-22 18:00:48,143) successfully insert task records.
[2023-10-22T18:00:48.143+0800] {viewers_reaction.py:451} INFO - successfully insert task records.
[2023-10-22T18:00:48.144+0800] {logging_mixin.py:151} INFO - successfully insert task records.
[2023-10-22T18:00:48.144+0800] {python.py:194} INFO - Done. Returned value was: None
[2023-10-22T18:00:48.156+0800] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=trick2g_insert_stats_dag, task_id=insert_stats_task, execution_date=20231022T100033, start_date=20231022T100046, end_date=20231022T100048
[2023-10-22T18:00:48.195+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-22T18:00:48.208+0800] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
