[2023-10-22T17:27:59.318+0800] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trick2g_insert_logs_dag.insert_logs_task manual__2023-10-22T09:27:48.126271+00:00 [queued]>
[2023-10-22T17:27:59.322+0800] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trick2g_insert_logs_dag.insert_logs_task manual__2023-10-22T09:27:48.126271+00:00 [queued]>
[2023-10-22T17:27:59.323+0800] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-22T17:27:59.328+0800] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_logs_task> on 2023-10-22 09:27:48.126271+00:00
[2023-10-22T17:27:59.332+0800] {standard_task_runner.py:57} INFO - Started process 367 to run task
[2023-10-22T17:27:59.336+0800] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'trick2g_insert_logs_dag', 'insert_logs_task', 'manual__2023-10-22T09:27:48.126271+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/dags_generator.py', '--cfg-path', '/tmp/tmpwqvxil7l']
[2023-10-22T17:27:59.337+0800] {standard_task_runner.py:85} INFO - Job 57: Subtask insert_logs_task
[2023-10-22T17:27:59.368+0800] {task_command.py:415} INFO - Running <TaskInstance: trick2g_insert_logs_dag.insert_logs_task manual__2023-10-22T09:27:48.126271+00:00 [running]> on host 7781ba1548ef
[2023-10-22T17:27:59.413+0800] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trick2g_insert_logs_dag' AIRFLOW_CTX_TASK_ID='insert_logs_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T09:27:48.126271+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T09:27:48.126271+00:00'
[2023-10-22T17:28:00.908+0800] {logging_mixin.py:151} INFO - logs to send :  {'logGroupName': '/apps/CloudWatchAgentLog/', 'logStreamName': '172.31.5.38_i-017e875e2d5439eeb', 'logEvents': [{'timestamp': 1697966880908, 'message': "completed 'start_tracking_livestream' tasks: ['2023-10-08T06:10:34+08:00', '2023-10-14T02:44:11+08:00', '2023-10-22T08:10:54+08:00', '2023-10-13T01:00:13+08:00', '2023-10-15T02:00:12+08:00', '2023-10-17T00:13:27+08:00', '2023-10-09T00:47:24+08:00', '2023-10-16T03:57:44+08:00']"}], 'sequenceToken': '49039859564690599725055054078646149945659986271648381932'}
[2023-10-22T17:28:02.069+0800] {logging_mixin.py:151} INFO - Response :  {'nextSequenceToken': '49644975533496134954111663955246761202053229467593081106', 'ResponseMetadata': {'RequestId': '7368e936-0898-444a-ad12-95b50d98a08c', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '7368e936-0898-444a-ad12-95b50d98a08c', 'content-type': 'application/x-amz-json-1.1', 'content-length': '80', 'date': 'Sun, 22 Oct 2023 09:28:01 GMT'}, 'RetryAttempts': 0}}
[2023-10-22T17:28:02.070+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:28:02.070+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:28:02.070+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:28:02.070+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:28:02.071+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:28:02.071+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:28:02.071+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:28:02.071+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:28:02.072+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:28:02.072+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:28:02.073+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:02.073+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:02.073+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:28:02.073+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:28:02.073+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:28:02.073+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:28:02.073+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:28:02.074+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:28:02.074+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:28:02.074+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:28:02.074+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:28:02.074+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:28:02.074+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:28:02.075+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:28:02.075+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:28:02.075+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:28:02.075+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:28:02.075+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:28:02.075+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:28:02.075+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:28:02.076+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:28:02.076+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:28:02.076+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:28:02.076+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:28:02.076+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:28:02.076+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:28:02.077+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:28:02.077+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:28:02.077+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:28:02.077+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:28:02.077+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:28:02.077+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:28:02.078+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:28:02.078+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:28:02.078+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:28:02.078+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:02.078+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:02.078+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:02.078+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:28:02.079+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:28:02.079+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:02.079+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:28:02.079+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:28:02.079+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:28:02.079+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:28:02.080+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:28:02.080+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:02.080+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:02.080+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:02.080+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:28:02.080+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:28:02.081+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:02.081+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:28:02.081+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:28:02.081+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:28:02.081+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:28:02.081+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:28:02.081+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:28:02.082+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:28:02.082+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 120, in insert_chat_logs
    dev_logger.info("completed 'start_tracking_livestream' tasks: ", start_tracking_livestream_records)
[2023-10-22T17:28:02.082+0800] {logging_mixin.py:151} WARNING - Message: "completed 'start_tracking_livestream' tasks: "
Arguments: (['2023-10-08T06:10:34+08:00', '2023-10-14T02:44:11+08:00', '2023-10-22T08:10:54+08:00', '2023-10-13T01:00:13+08:00', '2023-10-15T02:00:12+08:00', '2023-10-17T00:13:27+08:00', '2023-10-09T00:47:24+08:00', '2023-10-16T03:57:44+08:00'],)
[2023-10-22T17:28:02.082+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:28:02.082+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:28:02.082+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:28:02.083+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:28:02.083+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:28:02.083+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:28:02.083+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:28:02.083+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:28:02.084+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:28:02.084+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:28:02.084+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:02.084+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:02.084+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:28:02.084+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:28:02.085+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:28:02.085+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:28:02.085+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:28:02.085+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:28:02.085+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:28:02.085+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:28:02.086+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:28:02.086+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:28:02.086+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:28:02.086+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:28:02.086+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:28:02.086+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:28:02.086+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:28:02.087+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:28:02.087+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:28:02.087+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:28:02.087+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:28:02.087+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:28:02.087+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:28:02.087+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:28:02.088+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:28:02.088+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:28:02.088+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:28:02.088+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:28:02.088+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:28:02.088+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:28:02.088+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:28:02.089+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:28:02.089+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:28:02.089+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:28:02.089+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:28:02.089+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:02.089+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:02.090+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:02.090+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:28:02.090+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:28:02.090+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:02.090+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:28:02.090+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:28:02.090+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:28:02.091+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:28:02.091+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:28:02.091+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:02.091+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:02.091+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:02.091+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:28:02.092+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:28:02.092+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:02.092+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:28:02.092+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:28:02.092+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:28:02.092+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:28:02.092+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:28:02.093+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:28:02.093+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:28:02.093+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 120, in insert_chat_logs
    dev_logger.info("completed 'start_tracking_livestream' tasks: ", start_tracking_livestream_records)
[2023-10-22T17:28:02.093+0800] {logging_mixin.py:151} WARNING - Message: "completed 'start_tracking_livestream' tasks: "
Arguments: (['2023-10-08T06:10:34+08:00', '2023-10-14T02:44:11+08:00', '2023-10-22T08:10:54+08:00', '2023-10-13T01:00:13+08:00', '2023-10-15T02:00:12+08:00', '2023-10-17T00:13:27+08:00', '2023-10-09T00:47:24+08:00', '2023-10-16T03:57:44+08:00'],)
[2023-10-22T17:28:02.093+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:28:02.093+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:28:02.094+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:28:02.094+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:28:02.094+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:28:02.094+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:28:02.094+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:28:02.094+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:28:02.095+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:28:02.095+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:28:02.095+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:02.095+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:02.095+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:28:02.095+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:28:02.096+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:28:02.096+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:28:02.096+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:28:02.096+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:28:02.096+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:28:02.096+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:28:02.096+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:28:02.097+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:28:02.097+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:28:02.097+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:28:02.097+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:28:02.097+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:28:02.097+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:28:02.098+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:28:02.098+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:28:02.098+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:28:02.098+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:28:02.098+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:28:02.098+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:28:02.098+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:28:02.099+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:28:02.099+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:28:02.099+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:28:02.099+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:28:02.099+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:28:02.099+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:28:02.099+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:28:02.100+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:28:02.100+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:28:02.100+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:28:02.100+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:28:02.100+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:02.100+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:02.100+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:02.101+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:28:02.101+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:28:02.101+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:02.101+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:28:02.101+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:28:02.101+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:28:02.102+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:28:02.102+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:28:02.102+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:02.102+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:02.102+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:02.102+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:28:02.102+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:28:02.103+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:02.103+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:28:02.103+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:28:02.103+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:28:02.103+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:28:02.103+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:28:02.104+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:28:02.104+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:28:02.104+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 120, in insert_chat_logs
    dev_logger.info("completed 'start_tracking_livestream' tasks: ", start_tracking_livestream_records)
[2023-10-22T17:28:02.104+0800] {logging_mixin.py:151} WARNING - Message: "completed 'start_tracking_livestream' tasks: "
Arguments: (['2023-10-08T06:10:34+08:00', '2023-10-14T02:44:11+08:00', '2023-10-22T08:10:54+08:00', '2023-10-13T01:00:13+08:00', '2023-10-15T02:00:12+08:00', '2023-10-17T00:13:27+08:00', '2023-10-09T00:47:24+08:00', '2023-10-16T03:57:44+08:00'],)
[2023-10-22T17:28:02.104+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:28:02.104+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:28:02.105+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:28:02.105+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:28:02.105+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:28:02.105+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:28:02.105+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:28:02.105+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:28:02.106+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:28:02.106+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:28:02.106+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:02.106+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:02.106+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:28:02.107+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:28:02.107+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:28:02.107+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:28:02.107+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:28:02.107+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:28:02.107+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:28:02.107+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:28:02.108+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:28:02.108+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:28:02.108+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:28:02.108+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:28:02.108+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:28:02.108+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:28:02.109+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:28:02.109+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:28:02.109+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:28:02.109+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:28:02.109+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:28:02.109+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:28:02.109+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:28:02.110+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:28:02.110+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:28:02.110+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:28:02.110+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:28:02.110+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:28:02.110+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:28:02.110+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:28:02.111+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:28:02.111+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:28:02.111+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:28:02.111+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:28:02.111+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:28:02.111+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:02.111+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:02.112+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:02.112+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:28:02.112+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:28:02.112+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:02.112+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:28:02.112+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:28:02.113+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:28:02.113+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:28:02.113+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:28:02.113+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:02.113+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:02.113+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:02.113+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:28:02.114+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:28:02.114+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:02.114+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:28:02.114+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:28:02.114+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:28:02.114+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:28:02.115+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:28:02.115+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:28:02.115+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:28:02.115+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 120, in insert_chat_logs
    dev_logger.info("completed 'start_tracking_livestream' tasks: ", start_tracking_livestream_records)
[2023-10-22T17:28:02.115+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2023-10-22T17:28:02.115+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2023-10-22T17:28:02.115+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2023-10-22T17:28:02.116+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2023-10-22T17:28:02.116+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2023-10-22T17:28:02.116+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/log/file_task_handler.py", line 211, in emit
    self.handler.emit(record)
[2023-10-22T17:28:02.116+0800] {logging_mixin.py:151} WARNING - Message: "completed 'start_tracking_livestream' tasks: "
Arguments: (['2023-10-08T06:10:34+08:00', '2023-10-14T02:44:11+08:00', '2023-10-22T08:10:54+08:00', '2023-10-13T01:00:13+08:00', '2023-10-15T02:00:12+08:00', '2023-10-17T00:13:27+08:00', '2023-10-09T00:47:24+08:00', '2023-10-16T03:57:44+08:00'],)
[2023-10-22T17:28:02.414+0800] {logging_mixin.py:151} INFO - logs to send :  {'logGroupName': '/apps/CloudWatchAgentLog/', 'logStreamName': '172.31.5.38_i-017e875e2d5439eeb', 'logEvents': [{'timestamp': 1697966882414, 'message': "completed 'insert_logs_records' tasks: ['2023-10-15T02:00:12+08:00', '2023-10-08T06:10:34+08:00', '2023-10-14T02:44:11+08:00', '2023-10-13T01:00:13+08:00', '2023-10-09T00:47:24+08:00', '2023-10-16T03:57:44+08:00']"}], 'sequenceToken': '49039859564690599725055054078754689788166572234470619956'}
[2023-10-22T17:28:03.571+0800] {logging_mixin.py:151} INFO - Response :  {'nextSequenceToken': '49645354585863294957877294675640349294681794290699469586', 'ResponseMetadata': {'RequestId': 'ef8afde5-1811-41e4-99e1-928587b48d51', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': 'ef8afde5-1811-41e4-99e1-928587b48d51', 'content-type': 'application/x-amz-json-1.1', 'content-length': '80', 'date': 'Sun, 22 Oct 2023 09:28:02 GMT'}, 'RetryAttempts': 0}}
[2023-10-22T17:28:03.571+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:28:03.571+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:28:03.571+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:28:03.572+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:28:03.572+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:28:03.572+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:28:03.572+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:28:03.572+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:28:03.573+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:28:03.573+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:28:03.573+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:03.573+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:03.574+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:28:03.574+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:28:03.574+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:28:03.574+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:28:03.574+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:28:03.574+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:28:03.574+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:28:03.575+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:28:03.575+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:28:03.575+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:28:03.575+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:28:03.575+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:28:03.575+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:28:03.575+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:28:03.576+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:28:03.576+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:28:03.576+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:28:03.576+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:28:03.576+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:28:03.576+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:28:03.577+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:28:03.577+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:28:03.577+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:28:03.577+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:28:03.577+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:28:03.577+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:28:03.578+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:28:03.578+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:28:03.578+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:28:03.578+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:28:03.578+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:28:03.578+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:28:03.578+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:28:03.579+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:03.579+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:03.579+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:03.579+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:28:03.579+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:28:03.579+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:03.580+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:28:03.580+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:28:03.580+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:28:03.580+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:28:03.580+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:28:03.580+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:03.581+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:03.581+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:03.581+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:28:03.581+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:28:03.581+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:03.581+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:28:03.582+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:28:03.582+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:28:03.582+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:28:03.582+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:28:03.582+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:28:03.582+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:28:03.582+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 146, in insert_chat_logs
    dev_logger.info("completed 'insert_logs_records' tasks: ", insert_logs_records)
[2023-10-22T17:28:03.583+0800] {logging_mixin.py:151} WARNING - Message: "completed 'insert_logs_records' tasks: "
Arguments: (['2023-10-15T02:00:12+08:00', '2023-10-08T06:10:34+08:00', '2023-10-14T02:44:11+08:00', '2023-10-13T01:00:13+08:00', '2023-10-09T00:47:24+08:00', '2023-10-16T03:57:44+08:00'],)
[2023-10-22T17:28:03.583+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:28:03.583+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:28:03.583+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:28:03.583+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:28:03.583+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:28:03.583+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:28:03.584+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:28:03.584+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:28:03.584+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:28:03.584+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:28:03.584+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:03.585+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:03.585+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:28:03.585+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:28:03.585+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:28:03.585+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:28:03.585+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:28:03.586+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:28:03.586+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:28:03.586+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:28:03.586+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:28:03.586+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:28:03.586+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:28:03.586+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:28:03.587+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:28:03.587+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:28:03.587+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:28:03.587+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:28:03.587+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:28:03.587+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:28:03.587+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:28:03.588+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:28:03.588+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:28:03.588+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:28:03.588+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:28:03.588+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:28:03.588+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:28:03.589+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:28:03.589+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:28:03.589+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:28:03.589+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:28:03.589+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:28:03.589+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:28:03.589+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:28:03.590+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:28:03.590+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:03.590+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:03.590+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:03.590+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:28:03.590+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:28:03.590+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:03.591+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:28:03.591+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:28:03.591+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:28:03.591+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:28:03.591+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:28:03.591+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:03.592+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:03.592+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:03.592+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:28:03.592+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:28:03.592+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:03.592+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:28:03.592+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:28:03.593+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:28:03.593+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:28:03.593+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:28:03.593+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:28:03.593+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:28:03.593+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 146, in insert_chat_logs
    dev_logger.info("completed 'insert_logs_records' tasks: ", insert_logs_records)
[2023-10-22T17:28:03.593+0800] {logging_mixin.py:151} WARNING - Message: "completed 'insert_logs_records' tasks: "
Arguments: (['2023-10-15T02:00:12+08:00', '2023-10-08T06:10:34+08:00', '2023-10-14T02:44:11+08:00', '2023-10-13T01:00:13+08:00', '2023-10-09T00:47:24+08:00', '2023-10-16T03:57:44+08:00'],)
[2023-10-22T17:28:03.594+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:28:03.594+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:28:03.594+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:28:03.594+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:28:03.594+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:28:03.594+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:28:03.595+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:28:03.595+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:28:03.595+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:28:03.595+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:28:03.595+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:03.596+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:03.596+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:28:03.596+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:28:03.596+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:28:03.596+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:28:03.596+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:28:03.596+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:28:03.597+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:28:03.597+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:28:03.597+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:28:03.597+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:28:03.597+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:28:03.597+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:28:03.598+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:28:03.598+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:28:03.598+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:28:03.598+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:28:03.598+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:28:03.598+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:28:03.598+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:28:03.599+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:28:03.599+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:28:03.599+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:28:03.599+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:28:03.599+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:28:03.599+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:28:03.599+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:28:03.600+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:28:03.600+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:28:03.600+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:28:03.600+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:28:03.600+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:28:03.600+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:28:03.600+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:28:03.601+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:03.601+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:03.601+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:03.601+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:28:03.601+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:28:03.601+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:03.601+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:28:03.602+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:28:03.602+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:28:03.602+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:28:03.602+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:28:03.602+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:03.602+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:03.603+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:03.603+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:28:03.603+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:28:03.603+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:03.603+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:28:03.603+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:28:03.603+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:28:03.604+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:28:03.604+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:28:03.604+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:28:03.604+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:28:03.604+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 146, in insert_chat_logs
    dev_logger.info("completed 'insert_logs_records' tasks: ", insert_logs_records)
[2023-10-22T17:28:03.604+0800] {logging_mixin.py:151} WARNING - Message: "completed 'insert_logs_records' tasks: "
Arguments: (['2023-10-15T02:00:12+08:00', '2023-10-08T06:10:34+08:00', '2023-10-14T02:44:11+08:00', '2023-10-13T01:00:13+08:00', '2023-10-09T00:47:24+08:00', '2023-10-16T03:57:44+08:00'],)
[2023-10-22T17:28:03.605+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:28:03.605+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:28:03.605+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:28:03.605+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:28:03.605+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:28:03.605+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:28:03.605+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:28:03.606+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:28:03.606+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:28:03.606+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:28:03.606+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:03.606+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:03.607+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:28:03.607+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:28:03.607+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:28:03.607+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:28:03.607+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:28:03.607+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:28:03.608+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:28:03.608+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:28:03.608+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:28:03.608+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:28:03.608+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:28:03.608+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:28:03.608+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:28:03.609+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:28:03.609+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:28:03.609+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:28:03.609+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:28:03.609+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:28:03.609+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:28:03.609+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:28:03.610+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:28:03.610+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:28:03.610+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:28:03.610+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:28:03.610+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:28:03.610+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:28:03.610+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:28:03.611+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:28:03.611+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:28:03.611+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:28:03.611+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:28:03.611+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:28:03.611+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:28:03.611+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:03.612+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:03.612+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:03.612+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:28:03.612+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:28:03.612+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:03.612+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:28:03.613+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:28:03.613+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:28:03.613+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:28:03.613+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:28:03.613+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:03.613+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:03.613+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:03.614+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:28:03.614+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:28:03.615+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:03.615+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:28:03.615+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:28:03.615+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:28:03.615+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:28:03.615+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:28:03.616+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:28:03.616+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:28:03.616+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 146, in insert_chat_logs
    dev_logger.info("completed 'insert_logs_records' tasks: ", insert_logs_records)
[2023-10-22T17:28:03.616+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2023-10-22T17:28:03.617+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2023-10-22T17:28:03.617+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2023-10-22T17:28:03.617+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2023-10-22T17:28:03.617+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2023-10-22T17:28:03.617+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/log/file_task_handler.py", line 211, in emit
    self.handler.emit(record)
[2023-10-22T17:28:03.618+0800] {logging_mixin.py:151} WARNING - Message: "completed 'insert_logs_records' tasks: "
Arguments: (['2023-10-15T02:00:12+08:00', '2023-10-08T06:10:34+08:00', '2023-10-14T02:44:11+08:00', '2023-10-13T01:00:13+08:00', '2023-10-09T00:47:24+08:00', '2023-10-16T03:57:44+08:00'],)
[2023-10-22T17:28:03.771+0800] {logging_mixin.py:151} INFO - logs to send :  {'logGroupName': '/apps/CloudWatchAgentLog/', 'logStreamName': '172.31.5.38_i-017e875e2d5439eeb', 'logEvents': [{'timestamp': 1697966883772, 'message': "uncompleted insert_logs tasks: ['2023-10-17T00:13:27+08:00', '2023-10-22T08:10:54+08:00']"}], 'sequenceToken': '49039859564690599725055054078852477202039253331603389345'}
[2023-10-22T17:28:04.932+0800] {logging_mixin.py:151} INFO - Response :  {'nextSequenceToken': '49645309829851034416012494832531328390451625171210995202', 'ResponseMetadata': {'RequestId': '3637855b-8fba-468c-a5b5-2335c1bac6bd', 'HTTPStatusCode': 200, 'HTTPHeaders': {'x-amzn-requestid': '3637855b-8fba-468c-a5b5-2335c1bac6bd', 'content-type': 'application/x-amz-json-1.1', 'content-length': '80', 'date': 'Sun, 22 Oct 2023 09:28:04 GMT'}, 'RetryAttempts': 0}}
[2023-10-22T17:28:04.932+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:28:04.933+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:28:04.933+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:28:04.933+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:28:04.933+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:28:04.933+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:28:04.934+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:28:04.934+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:28:04.935+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:28:04.935+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:28:04.935+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:04.935+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:04.935+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:28:04.935+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:28:04.936+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:28:04.936+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:28:04.936+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:28:04.936+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:28:04.936+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:28:04.936+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:28:04.936+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:28:04.937+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:28:04.937+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:28:04.937+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:28:04.937+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:28:04.937+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:28:04.938+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:28:04.938+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:28:04.938+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:28:04.938+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:28:04.938+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:28:04.938+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:28:04.939+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:28:04.939+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:28:04.939+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:28:04.939+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:28:04.939+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:28:04.939+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:28:04.940+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:28:04.940+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:28:04.940+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:28:04.940+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:28:04.940+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:28:04.941+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:28:04.941+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:28:04.941+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:04.941+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:04.941+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:04.941+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:28:04.941+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:28:04.942+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:04.942+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:28:04.942+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:28:04.942+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:28:04.942+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:28:04.943+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:28:04.943+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:04.943+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:04.943+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:04.943+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:28:04.943+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:28:04.943+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:04.944+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:28:04.944+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:28:04.944+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:28:04.944+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:28:04.944+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:28:04.944+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:28:04.944+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:28:04.945+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 154, in insert_chat_logs
    dev_logger.info("uncompleted insert_logs tasks: ", uncompleted_tasks)
[2023-10-22T17:28:04.945+0800] {logging_mixin.py:151} WARNING - Message: 'uncompleted insert_logs tasks: '
Arguments: (['2023-10-17T00:13:27+08:00', '2023-10-22T08:10:54+08:00'],)
[2023-10-22T17:28:04.945+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:28:04.945+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:28:04.945+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:28:04.945+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:28:04.946+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:28:04.946+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:28:04.946+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:28:04.946+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:28:04.946+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:28:04.947+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:28:04.947+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:04.947+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:04.947+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:28:04.947+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:28:04.947+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:28:04.947+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:28:04.948+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:28:04.948+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:28:04.948+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:28:04.948+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:28:04.948+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:28:04.948+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:28:04.949+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:28:04.949+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:28:04.949+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:28:04.949+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:28:04.949+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:28:04.949+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:28:04.949+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:28:04.950+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:28:04.950+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:28:04.950+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:28:04.950+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:28:04.950+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:28:04.950+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:28:04.951+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:28:04.951+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:28:04.951+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:28:04.951+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:28:04.951+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:28:04.951+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:28:04.951+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:28:04.952+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:28:04.952+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:28:04.952+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:28:04.952+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:04.952+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:04.952+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:04.952+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:28:04.953+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:28:04.953+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:04.953+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:28:04.953+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:28:04.953+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:28:04.953+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:28:04.954+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:28:04.954+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:04.954+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:04.954+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:04.954+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:28:04.954+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:28:04.954+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:04.955+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:28:04.955+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:28:04.955+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:28:04.955+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:28:04.955+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:28:04.955+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:28:04.956+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:28:04.956+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 154, in insert_chat_logs
    dev_logger.info("uncompleted insert_logs tasks: ", uncompleted_tasks)
[2023-10-22T17:28:04.956+0800] {logging_mixin.py:151} WARNING - Message: 'uncompleted insert_logs tasks: '
Arguments: (['2023-10-17T00:13:27+08:00', '2023-10-22T08:10:54+08:00'],)
[2023-10-22T17:28:04.956+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:28:04.956+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:28:04.956+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:28:04.956+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:28:04.957+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:28:04.957+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:28:04.957+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:28:04.957+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:28:04.957+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:28:04.958+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:28:04.958+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:04.958+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:04.958+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:28:04.958+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:28:04.958+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:28:04.959+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:28:04.959+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:28:04.959+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:28:04.959+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:28:04.959+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:28:04.959+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:28:04.959+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:28:04.960+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:28:04.960+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:28:04.960+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:28:04.960+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:28:04.960+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:28:04.960+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:28:04.960+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:28:04.961+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:28:04.961+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:28:04.961+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:28:04.961+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:28:04.961+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:28:04.961+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:28:04.962+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:28:04.962+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:28:04.962+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:28:04.962+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:28:04.962+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:28:04.962+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:28:04.963+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:28:04.963+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:28:04.963+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:28:04.963+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:28:04.963+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:04.963+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:04.963+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:04.964+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:28:04.964+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:28:04.964+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:04.964+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:28:04.964+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:28:04.964+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:28:04.965+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:28:04.965+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:28:04.965+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:04.965+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:04.965+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:04.965+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:28:04.965+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:28:04.966+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:04.966+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:28:04.966+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:28:04.966+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:28:04.966+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:28:04.966+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:28:04.966+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:28:04.967+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:28:04.967+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 154, in insert_chat_logs
    dev_logger.info("uncompleted insert_logs tasks: ", uncompleted_tasks)
[2023-10-22T17:28:04.967+0800] {logging_mixin.py:151} WARNING - Message: 'uncompleted insert_logs tasks: '
Arguments: (['2023-10-17T00:13:27+08:00', '2023-10-22T08:10:54+08:00'],)
[2023-10-22T17:28:04.967+0800] {logging_mixin.py:151} WARNING - --- Logging error ---
[2023-10-22T17:28:04.967+0800] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2023-10-22T17:28:04.967+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
[2023-10-22T17:28:04.968+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
[2023-10-22T17:28:04.968+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
[2023-10-22T17:28:04.968+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
[2023-10-22T17:28:04.968+0800] {logging_mixin.py:151} WARNING - TypeError: not all arguments converted during string formatting
[2023-10-22T17:28:04.968+0800] {logging_mixin.py:151} WARNING - Call stack:
[2023-10-22T17:28:04.969+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2023-10-22T17:28:04.969+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/__main__.py", line 59, in main
    args.func(args)
[2023-10-22T17:28:04.969+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:04.969+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:04.969+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2023-10-22T17:28:04.969+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/celery_command.py", line 242, in worker
    celery_app.worker_main(options)
[2023-10-22T17:28:04.969+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 388, in worker_main
    self.start(argv=argv)
[2023-10-22T17:28:04.970+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/base.py", line 368, in start
    celery.main(args=argv, standalone_mode=False)
[2023-10-22T17:28:04.970+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2023-10-22T17:28:04.970+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2023-10-22T17:28:04.970+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2023-10-22T17:28:04.970+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2023-10-22T17:28:04.970+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2023-10-22T17:28:04.971+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
[2023-10-22T17:28:04.971+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2023-10-22T17:28:04.971+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2023-10-22T17:28:04.971+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2023-10-22T17:28:04.971+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2023-10-22T17:28:04.971+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2023-10-22T17:28:04.971+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2023-10-22T17:28:04.972+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2023-10-22T17:28:04.972+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1045, in __init__
    self._create_worker_process(i)
[2023-10-22T17:28:04.972+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2023-10-22T17:28:04.972+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 1157, in _create_worker_process
    w.start()
[2023-10-22T17:28:04.972+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2023-10-22T17:28:04.972+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2023-10-22T17:28:04.972+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2023-10-22T17:28:04.973+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2023-10-22T17:28:04.973+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2023-10-22T17:28:04.973+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2023-10-22T17:28:04.973+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 291, in __call__
    sys.exit(self.workloop(pid=pid))
[2023-10-22T17:28:04.973+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/billiard/pool.py", line 361, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2023-10-22T17:28:04.973+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 675, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2023-10-22T17:28:04.973+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 477, in trace_task
    R = retval = fun(*args, **kwargs)
[2023-10-22T17:28:04.974+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
[2023-10-22T17:28:04.974+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 123, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2023-10-22T17:28:04.974+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 157, in _execute_in_fork
    args.func(args)
[2023-10-22T17:28:04.974+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:04.974+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:04.974+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:04.974+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 208, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2023-10-22T17:28:04.975+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 270, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2023-10-22T17:28:04.975+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:04.975+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 289, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2023-10-22T17:28:04.975+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/job.py", line 318, in execute_job
    ret = execute_callable()
[2023-10-22T17:28:04.975+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/jobs/local_task_job_runner.py", line 159, in _execute
    self.task_runner.start()
[2023-10-22T17:28:04.975+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 45, in start
    self.process = self._start_by_fork()
[2023-10-22T17:28:04.975+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/task/task_runner/standard_task_runner.py", line 97, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2023-10-22T17:28:04.976+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2023-10-22T17:28:04.976+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/cli.py", line 113, in wrapper
    return f(*args, **kwargs)
[2023-10-22T17:28:04.976+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 430, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2023-10-22T17:28:04.976+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 210, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2023-10-22T17:28:04.976+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/cli/commands/task_command.py", line 289, in _run_raw_task
    return ti._run_raw_task(
[2023-10-22T17:28:04.976+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
[2023-10-22T17:28:04.977+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
[2023-10-22T17:28:04.977+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1679, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2023-10-22T17:28:04.977+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/models/taskinstance.py", line 1742, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
[2023-10-22T17:28:04.977+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
[2023-10-22T17:28:04.977+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
[2023-10-22T17:28:04.977+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
[2023-10-22T17:28:04.977+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
[2023-10-22T17:28:04.978+0800] {logging_mixin.py:151} WARNING -   File "/opt/***/plugins/features/viewers_reaction.py", line 154, in insert_chat_logs
    dev_logger.info("uncompleted insert_logs tasks: ", uncompleted_tasks)
[2023-10-22T17:28:04.978+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
[2023-10-22T17:28:04.978+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
[2023-10-22T17:28:04.978+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
[2023-10-22T17:28:04.978+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
[2023-10-22T17:28:04.978+0800] {logging_mixin.py:151} WARNING -   File "/usr/local/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
[2023-10-22T17:28:04.978+0800] {logging_mixin.py:151} WARNING -   File "/home/***/.local/lib/python3.10/site-packages/***/utils/log/file_task_handler.py", line 211, in emit
    self.handler.emit(record)
[2023-10-22T17:28:04.979+0800] {logging_mixin.py:151} WARNING - Message: 'uncompleted insert_logs tasks: '
Arguments: (['2023-10-17T00:13:27+08:00', '2023-10-22T08:10:54+08:00'],)
[2023-10-22T17:28:04.979+0800] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
  File "/opt/airflow/plugins/features/viewers_reaction.py", line 159, in insert_chat_logs
    with open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/chat_logs/2023-10-17T00:13:27+08:00_trick2g.log'
[2023-10-22T17:28:04.986+0800] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=trick2g_insert_logs_dag, task_id=insert_logs_task, execution_date=20231022T092748, start_date=20231022T092759, end_date=20231022T092804
[2023-10-22T17:28:04.992+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 57 for task insert_logs_task ([Errno 2] No such file or directory: '/opt/airflow/dags/chat_logs/2023-10-17T00:13:27+08:00_trick2g.log'; 367)
[2023-10-22T17:28:05.017+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T17:28:05.028+0800] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
