[2023-10-22T17:26:04.178+0800] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trick2g_insert_logs_dag.insert_logs_task manual__2023-10-22T09:25:41.098836+00:00 [queued]>
[2023-10-22T17:26:04.182+0800] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trick2g_insert_logs_dag.insert_logs_task manual__2023-10-22T09:25:41.098836+00:00 [queued]>
[2023-10-22T17:26:04.183+0800] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-22T17:26:04.188+0800] {taskinstance.py:1380} INFO - Executing <Task(_PythonDecoratedOperator): insert_logs_task> on 2023-10-22 09:25:41.098836+00:00
[2023-10-22T17:26:04.193+0800] {standard_task_runner.py:57} INFO - Started process 328 to run task
[2023-10-22T17:26:04.197+0800] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'trick2g_insert_logs_dag', 'insert_logs_task', 'manual__2023-10-22T09:25:41.098836+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/dags_generator.py', '--cfg-path', '/tmp/tmp1x9fy33c']
[2023-10-22T17:26:04.198+0800] {standard_task_runner.py:85} INFO - Job 56: Subtask insert_logs_task
[2023-10-22T17:26:04.232+0800] {task_command.py:415} INFO - Running <TaskInstance: trick2g_insert_logs_dag.insert_logs_task manual__2023-10-22T09:25:41.098836+00:00 [running]> on host 7781ba1548ef
[2023-10-22T17:26:04.277+0800] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trick2g_insert_logs_dag' AIRFLOW_CTX_TASK_ID='insert_logs_task' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T09:25:41.098836+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T09:25:41.098836+00:00'
[2023-10-22T17:26:05.208+0800] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dags_generator.py", line 64, in insert_logs_task
    analyser.insert_chat_logs()
  File "/opt/airflow/plugins/features/viewers_reaction.py", line 119, in insert_chat_logs
    send_log("completed 'start_tracking_livestream' tasks: ", start_tracking_livestream_records)
TypeError: send_log() takes 1 positional argument but 2 were given
[2023-10-22T17:26:05.215+0800] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=trick2g_insert_logs_dag, task_id=insert_logs_task, execution_date=20231022T092541, start_date=20231022T092604, end_date=20231022T092605
[2023-10-22T17:26:05.254+0800] {standard_task_runner.py:104} ERROR - Failed to execute job 56 for task insert_logs_task (send_log() takes 1 positional argument but 2 were given; 328)
[2023-10-22T17:26:05.293+0800] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T17:26:05.305+0800] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
